/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KundenRouteRouteImport } from './routes/kunden/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KundenIndexRouteImport } from './routes/kunden/index'
import { Route as KundenIdRouteImport } from './routes/kunden/$id'

const KundenRouteRoute = KundenRouteRouteImport.update({
  id: '/kunden',
  path: '/kunden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KundenIndexRoute = KundenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KundenRouteRoute,
} as any)
const KundenIdRoute = KundenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KundenRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kunden': typeof KundenRouteRouteWithChildren
  '/kunden/$id': typeof KundenIdRoute
  '/kunden/': typeof KundenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kunden/$id': typeof KundenIdRoute
  '/kunden': typeof KundenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kunden': typeof KundenRouteRouteWithChildren
  '/kunden/$id': typeof KundenIdRoute
  '/kunden/': typeof KundenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kunden' | '/kunden/$id' | '/kunden/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kunden/$id' | '/kunden'
  id: '__root__' | '/' | '/kunden' | '/kunden/$id' | '/kunden/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KundenRouteRoute: typeof KundenRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kunden': {
      id: '/kunden'
      path: '/kunden'
      fullPath: '/kunden'
      preLoaderRoute: typeof KundenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunden/': {
      id: '/kunden/'
      path: '/'
      fullPath: '/kunden/'
      preLoaderRoute: typeof KundenIndexRouteImport
      parentRoute: typeof KundenRouteRoute
    }
    '/kunden/$id': {
      id: '/kunden/$id'
      path: '/$id'
      fullPath: '/kunden/$id'
      preLoaderRoute: typeof KundenIdRouteImport
      parentRoute: typeof KundenRouteRoute
    }
  }
}

interface KundenRouteRouteChildren {
  KundenIdRoute: typeof KundenIdRoute
  KundenIndexRoute: typeof KundenIndexRoute
}

const KundenRouteRouteChildren: KundenRouteRouteChildren = {
  KundenIdRoute: KundenIdRoute,
  KundenIndexRoute: KundenIndexRoute,
}

const KundenRouteRouteWithChildren = KundenRouteRoute._addFileChildren(
  KundenRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KundenRouteRoute: KundenRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
