/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KundenRouteImport } from './routes/kunden'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KundenIdRouteImport } from './routes/kunden.$id'

const KundenRoute = KundenRouteImport.update({
  id: '/kunden',
  path: '/kunden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KundenIdRoute = KundenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KundenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kunden': typeof KundenRouteWithChildren
  '/kunden/$id': typeof KundenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kunden': typeof KundenRouteWithChildren
  '/kunden/$id': typeof KundenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kunden': typeof KundenRouteWithChildren
  '/kunden/$id': typeof KundenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kunden' | '/kunden/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kunden' | '/kunden/$id'
  id: '__root__' | '/' | '/kunden' | '/kunden/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KundenRoute: typeof KundenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kunden': {
      id: '/kunden'
      path: '/kunden'
      fullPath: '/kunden'
      preLoaderRoute: typeof KundenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunden/$id': {
      id: '/kunden/$id'
      path: '/$id'
      fullPath: '/kunden/$id'
      preLoaderRoute: typeof KundenIdRouteImport
      parentRoute: typeof KundenRoute
    }
  }
}

interface KundenRouteChildren {
  KundenIdRoute: typeof KundenIdRoute
}

const KundenRouteChildren: KundenRouteChildren = {
  KundenIdRoute: KundenIdRoute,
}

const KundenRouteWithChildren =
  KundenRoute._addFileChildren(KundenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KundenRoute: KundenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
